Jhzlo
bitbybit-server/java-racingcar-6 pull request #2
Opened 2024-09-06 11:12 UTC by JHZLO

```text           
\---src
    +---main
    |   \---java
    |       \---racingcar
    |           |   Application.java
    |           |   
    |           +---constant
    |           |       ErrorMessage.java
    |           |       ViewMessage.java
    |           |       
    |           +---controller
    |           |       RacingCarController.java
    |           |       
    |           +---domain
    |           |   |   Movable.java
    |           |   |   RandomNumberGenerator.java
    |           |   |   
    |           |   +---dto
    |           |   |       CarsDTO.java
    |           |   |       
    |           |   \---model
    |           |           Car.java
    |           |           Cars.java
    |           |           
    |           +---exception
    |           |       InputCarNamesValidator.java
    |           |       InputRoundValidator.java
    |           |       
    |           +---service
    |           |       GameService.java
    |           |       
    |           \---view
    |                   InputView.java
    |                   OutputView.java
    |                   
    \---test
        \---java
            |   ApplicationTest.java
            |   
            +---racingcar
            |   +---domain
            |   |       CarsTest.java
            |   |       CarTest.java
            |   |       MovableTest.java
            |   |       RandomNumberGeneratorTest.java
            |   |       
            |   \---view
            |           InputCarsTest.java
            |           InputRoundTest.java
            |           
            \---study
                    StringTest.java
                    
```

2024-09-06 14:44 UTC, digitpic commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    private ErrorMessage() {} // 인스턴스화 방지
좋은 처리입니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/constant/ErrorMessage.java
> +}
이야기 많이 나눴던 부분이긴 하지만
`Enum` 과 `toString` 메서드 오버라이딩을 이용해보는 건 어떨까요?

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/constant/ViewMessage.java
> +}
여기도 `Enum` `toString` 적용해보면 더 좋아질 수 있을 것 같아보여요

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
게임 흐름을 적절한 단계로 나누어 분리한 모습 좋습니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
View나 Service의 메서드를 static으로 선언하여 인스턴스를 생성하지 않고 호출하는 방식에 대해서는 어떻게 생각하시는지 궁금합니다
인스턴스를 꼭 생성해서 처리를 해야 되는지, 이에 대해 어떻게 생각하시는지 여쭤보고 싶습니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/InputView.java
> +    }
여기도 마찬가지로 테스트를 위한 메서드를 만들 필요가 있는지 궁금합니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/InputView.java
> +                .map(String::trim) // 각 이름의 앞뒤 공백 제거
이번 우테코는 자바 17 버전 기준이니 `String.trim()` 보다는 자바 11 버전 이후부터 사용할 수 있는 `String.strip()` 을 추천드립니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/InputView.java
> +    }
`사용자의 자동차 이름에 대한 입력` 에 쉼표가 없는 경우도 생각해 처리하는 방향이 더 좋을 거 같습니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/InputView.java
> +    }
테스트 코드는 기능 동작에 문제가 없는지를 파악하기 위해 작성한다고 생각하고 있습니다
테스트를 위한 메서드를 만들 필요가 있는지 궁금합니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/OutputView.java
> +                System.out.println(car.getCarName() + " : " + "-".repeat(car.getDistance()))
`String.repeat()` 메서드 활용 좋습니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println();  // 라운드마다 결과 구분을 위한 빈 줄 출력
이런 부분에 있어서 `View` 를 사용해야 할지 말아야 할지 고민이 되었습니다
저 또한 고민하다 `System.out.println()` 사용했습니다

이 부분에 대해 @JHZLO 님은 어떻게 생각하시나요?

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/view/OutputView.java
> +    }
`Stream` 활용 좋습니다
확실히 가독성이 좋아지네요

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
이 부분을 다시 보니 생각나는 점이 하나 있습니다

`하나의 메서드는 하나의 일을 처리한다고 한다` 고 되어 있는데
`inputCarNames()` 의 경우 `자동차 이름` 을 입력 받은 뒤, `자동차 인스턴스` 를 생성하고 있습니다
위 원칙에 따른다면 `입력 받는 메서드` , `입력 처리 메서드` 로 나누어야 하는가? 에 대해 고민하게 되었습니다

이에 대해 @JHZLO 님은 어떻게 생각하시는지 알려주시면 감사하겠습니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +}
`DTO` 를 사용한 이유에 대해 알고 싶습니다

`Controller` 에서 `DTO` 를 통해 `Cars` `Model` 을 생성하셨던데
`Cars` `Model` 을 바로 생성하지 않은 이유가 궁금합니다

2024-09-08 07:15 UTC, cueon commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +    }
기본 생성자는 생략 가능합니다
따로 남겨둔 이유가 있을까요?

2024-09-08 07:16 UTC, digitpic commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    public static final String INPUT_CAR_NAMES_MIN = "자동차 이름은 최소 2개 이상이어야 합니다.";
리터럴 2 대신 상수로 대체해보는 건 어떨까요?

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    public static final String INPUT_CAR_NAMES_MIN = "자동차 이름은 최소 2개 이상이어야 합니다.";
리터럴 2 대신 상수로 대체해보는 건 어떨까요?

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    public static final String INVALID_NEGATIVE = "시도 횟수는 1 이상이어야 합니다.";
리터럴 1 대신 상수로 대체 해보는 건 어떨까요?

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
한 줄로 끝내는 방법과 아래와 같이 단계를 나누어 처리하는 방법 중 어떤 게 더 낫다고 생각하시나요?
```suggestion
// 우승자 계산 및 출력
private void printWinners() {
    List<Car> winners = gameService.chooseWinners(cars);
    outputView.printWinners(winners); // 우승자 출력
}
```

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/domain/model/Car.java
> +    private int distance = 0;
리터럴은 지양하는 게 좋을 거 같아요

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/domain/RandomNumberGenerator.java
> +}
저는 `RandomNumberGenerator` 클래스가 `Service` 또는 `Car` `Model` 에 속해야 할 로직으로 보입니다
어떻게 생각하시나요?

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/domain/RandomNumberGenerator.java
> +    private static final int RANDOM_NUM_MAX = 9;
다음 주차에는 모든 상수를 `Enum` 으로 만들어 보는 거 어떠신가요??

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/domain/Movable.java
> +    }
`RandomNumberGenerator` 클래스의 인스턴스를 생성한 이유에 대해 알고 싶습니다

1. 인스턴스를 생성하여 사용하는 경우
2. 인스턴스를 생성하지 않고 클래스 자체를 사용하는 경우

위 두 가지 경우의 차이점은 무엇인가요?

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/domain/Movable.java
> +}
저라면 `Car` `Model` 의 메서드로 구성했을 거 같은데
`Movable` 클래스를 따로 생성한 이유가 궁금합니다

2024-09-08 07:58 UTC, digitpic commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    public static final String INVALID_CAR_NAME_MIN = "자동차 이름은 5자 이하만 가능합니다.";
리터럴 5 대신 상수로 대체해보는 건 어떨까요?

2024-09-08 08:12 UTC, digitpic commented on src/main/java/racingcar/domain/model/Cars.java
> +    private final List<Car> carList;
변수명에 자료구조를 적는 행위는 지양하라고 알고 있습니다
자료구조가 변경되면 변수명도 바꿔줘야 하기 때문입니다
```java
List<Car> carList
Set<Car> carSet
```

2024-09-08 08:36 UTC, JHZLO commented on src/main/java/racingcar/constant/ErrorMessage.java
> +}
안그래도 다음 주차에서는 상수를 `Enum` 으로 관리하는 것이 과제이던데,

다음 주차 때 적용해보도록 하겠습니다!

2024-09-08 10:35 UTC, JHZLO commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
좋은 지적입니다.

처음에는 기본생성자를 사용하여 인스턴스를 생성하여 `강한 결합`을 통한
`불변성과 안정성`을 강조하려고 하였습니다.

그래서 `InputView`와 `OutputView`와 같이 `불변성`이 대표되는 객체는 위와 같은 방식으로 `안정성`을 강화하였습니다.

그러다가 `Service`계층을 구성하게 되었고 이번엔 `가독성` 측면과 `Service`계층이 
Controller에 의존한다는 것을 보여주기 위해 위와 같이 `GameService` 인스턴스를 생성하게 되었습니다.

---

그러나 규원님의 질문을 통해 객체를 가져오는 방법은 다음과 같이 세 가지의 방법이 있다는 것을 알게 되었고

`직접 객체 선언 (강한 결합)`,
 `의존성 주입 (느슨한 결합)`, 
 `static 메서드 선언`

이에 대해 조금 더 공부를 해보았고 다음과 같이 정리 하였습니다.

---
1. 직접 객체 선언
- 직관적이고 간단한 코드 & 불변성과 안정성
- 강한 결합이기에 유연성과 확장성이 떨어짐 -> 의존성 주입 불가능

2. **의존성 주입** 
- 느슨한 결합 -> 객체 간의 의존도를 낮추고 유연성과 유지보수 측면에서 향상
- mocking을 통한 유닛테스트 가능 -> 확장성 측면에서도 향상

3. static 메서드를 통한 인스턴스 생성
- 메모리는 적게 사용 & 간단한 호출
- 객체 지향적이지 않음
- 상태(state)가 필요하거나 저장해야하는 경우 부적합 -> GameService는 부적합
- 의존성 주입이 불가능하여 mocking을 통한 유닛 테스트가 까다로움 -> 확장성 측면에서도 다소 떨어짐

---

따라서 다음과 같이

```java
public class RacingCarController {
    private final GameService gameService;

    // 생성자를 통해 의존성 주입
    public RacingCarController(GameService gameService) {
        this.gameService = gameService;
    }
}
```
`GameService`처럼 `게임의 로직`과 `state(상태)`를 관리해줘야하는 객체는 위의 코드와 같이
기본 생성자를 사용하여 `의존성 주입`을 진행한다면 `객체지향적인 설계`를 보다 더 잘 나타내고
`유연성`과 `확장성` 그리고 `유지보수`의 측면에서까지 모두 이점을 챙길 수 있을 것 같다는 생각이 들었습니다.

---

@digitpic 님은 이러한 객체를 가져오는 방식에 대해서 어떻게 생각하시는지 궁금합니다.

- 객체의 특성을 반영하여 각각의 객체마다 가져오는 방식을 다르게 해야하는지 (or 통일 시켜야하는지)
-  어떤 방식으로 객체를 가져오는 것을 선호하는지

2024-09-08 10:41 UTC, JHZLO commented on src/main/java/racingcar/view/InputView.java
> +    }
commit의 흐름을 보시면 아시겠지만 

원래는 `InputView` 객체에서
 `inputRound() 메서드` 안에  `입력 처리`와 `Validation 처리`가 전부 들어가있는 로직이였습니다.

그러다 보니 입력값만 가지고 `Validation`을 진행하여 테스트하는 것이 불가능하여 
테스트를 위한 단위로 쪼갠 과정입니다!

그리고 테스트 코드에서의 `가독성`을 높이기 위해 `inputRoundForTest`로 메서드를 정의하였습니다.

이렇게 구성한 것은 단순히 저의 생각이기에,
@digitpic 님은 이러한 방식에 대해서 어떻게 생각하시는지 궁금합니다.

2024-09-08 10:41 UTC, JHZLO commented on src/main/java/racingcar/view/InputView.java
> +                .map(String::trim) // 각 이름의 앞뒤 공백 제거
좋은 인사이트 감사합니다! 참고하겠습니다.

2024-09-08 10:46 UTC, JHZLO commented on src/main/java/racingcar/view/InputView.java
> +    }
만약 쉼표가 없더라면,
return되는 List의 size()를 반환했을 때 **1**의 값이 반환될 것입니다.

이렇게 되면 `Input`이후에 진행되는 `Validation` 로직에서
``` java
if (carNames.size() < 1) {
            throw new IllegalArgumentException(INPUT_CAR_NAMES_MIN);
        }
```
위의 코드에 따라 예외처리가 된다고 생각하여 쉼표가 없는 경우는 따로 생각해보지 않았습니다.

이럼에도 불구하고 쉼표가 없는 경우를 처리해야하는 이유가 따로 있을까요?

2024-09-08 10:48 UTC, JHZLO commented on src/main/java/racingcar/view/InputView.java
> +    }
단순히 테스트 코드의 `가독성`을 올리기 위해 작성하였던 것 같았습니다.

테스트 코드의 `가독성`은 그렇게 중요하지 않나요?
`기능에만 초점을 두는 것`이 맞는 방향인건지 알려주시면 감사하겠습니다!

2024-09-08 11:04 UTC, JHZLO commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
규원님의 말대로 `입력 받는 메서드`, `입력 처리 메서드` 
두 개를 서로 다른 역할로 나누고 메서드를 분리하는 것도 좋은 방법인 것 같습니다.

---

**중요한 것은 해당 객체가 어떤 역할을 담당하는지에 따라 보이는 관점이 다른 것 같습니다.**

---

 해당 객체는 `Controller`이고 
`Controller`는 `애플리케이션의 흐름`을 잘 나타내줘야 한다고 생각합니다.

애플리케이션의 흐름만 두고 봤을 때는 기능의 단위를 쪼갤 때 
`보이는 흐름` 그대로 쪼개야한다고 생각합니다.

1. 사용자로부터 `차 이름을 입력`을 받는다.
2. 사용자로부터 `시도 횟수를 입력` 받는다.
3. `경주`를 시작한다.
4. `우승자`를 출력한다.

규원님의 말처럼 `입력 받는 메서드`와 `입력 처리 메서드` 두 개는 내부 비즈니스 로직에 해당된다고 생각합니다.
고로, 애플리케이션의 전체적인 흐름에서 `보이지 않는 부분`이라고 생각합니다.

그래서 저는 이렇게 기능을 보이는 흐름대로 위와 같이 나누었고,

> 하나의 메서드는 하나의 일을 처리한다.

Controller에서 바라보는 관점으로는 메서드가 수행하는 `하나의 일`을
`자동차 이름`을 입력 받고 `인스턴스`를 생성하는 부분까지로 바라보고 구성하였습니다.

2024-09-08 11:07 UTC, JHZLO commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println();  // 라운드마다 결과 구분을 위한 빈 줄 출력
혹시 어느부분에서 고민이 되셨던건지 조금 더 자세하게 설명해주시면 감사하겠습니다!

2024-09-08 11:08 UTC, JHZLO commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    public static final String INPUT_CAR_NAMES_MIN = "자동차 이름은 최소 2개 이상이어야 합니다.";
오.. 거기까진 생각해보지 못했는데 좋은 것 같습니다.

추후에 확장성 측면에서도 유의미해보이네요!! 감사합니다.

2024-09-08 11:23 UTC, JHZLO commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
원래는 규원님의 코드처럼 두 줄이였다가 간단한 로직이라 한 줄로 변경한 코드인데,

`확장성`의 측면에서 바라본다면, 
`단계를 나누어서 작성하는 것`이 추후에 winners 값을 더 가공하거나 추가 로직이 필요할 때 
중간 변수 사용이 유리하다고 생각하기 때문에 `단계를 나누어 처리하는 방법`이 더 나은 것 같네요!

@digitpic 님은 어떻게 생각하시나요?

2024-09-08 11:25 UTC, JHZLO commented on src/main/java/racingcar/domain/model/Car.java
> +    private int distance = 0;
`distance` 라는 변수는 특성상 `gameRound`마다 변경되는 값이기에 `상수`를 사용하지 않았습니다.
`상수`는 변경되지 않아야 하는 값을 의미한다고 생각하였습니다.

그래서 최대한 `안정성`을 보장하기 위해 접근 제어자를 `private`로 구성하여 리터럴을 사용하게 되었습니다.

@digitpic 님은 이러한 가변적인 값들에 대해서 어떻게 처리하시나요?

2024-09-08 12:10 UTC, digitpic commented on src/main/java/racingcar/view/InputView.java
> +    }
물론 테스트 코드에서도 가독성은 중요하다고 생각합니다

우리는 도메인 로직에 대한 단위 테스트를 작성해야 합니다
그렇기에 UI에 대한 테스트는 진행하지 않습니다

제가 생각하기로는 `View` 에 로직이 담겨 있다보니 이런 상황이 벌어지게 되었다고 생각합니다

저는 기본적으로 테스트를 위한 메서드를 따로 만들어 본 경험이 없고
자바 기본 패키지에서도 본 적이 없었습니다
그렇기에 의문이 들었습니다

오로지 테스트를 위한 메서드 작성이 필요하다고 생각하시는지 궁금합니다

2024-09-08 12:11 UTC, digitpic commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println();  // 라운드마다 결과 구분을 위한 빈 줄 출력
한 줄에 대해서만 코멘트를 달았더니 4줄에 대한 코멘트가 달아졌군요..

`System.out.println()` 과 같이 한 줄 내림이 필요한 경우를 이야기 했던 겁니다

2024-09-08 12:25 UTC, digitpic commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
아 이해했습니다

사용자의 입장에서 `보이는 부분` 을 `Controller` 에 작성하고
`보이지 않는 부분` 은 내부적으로 처리했다는 이야기군요

이 경우 하나의 메서드가 단일 목적을 위한 행위를 한다고 할지라도 여러 기능을 수행하고 있습니다

아래와 같이 처리해보는 건 어떨까요?
`Controller` 에는 `inputCarNames` 을 그대로 작성하지만

```java
List<String> carNames = inputView.inputCarNames();
```

```java
cars = new CarsDTO(carNames).getCars();
```

위 두 라인은 두 개의 메서드로 분리해 `inputCarNames` 메서드 내부에 적어주는 방식입니다
이렇게 되면 하나의 메서드는 하나의 기능을 수행하면서 `Controller` 에서는 흐름만을 나타내기 좋지 않을까 싶습니다

@JHZLO 님은 어떻게 생각하시나요?

2024-09-08 13:11 UTC, digitpic commented on src/main/java/racingcar/view/InputView.java
> +    }
아 그런 식으로 처리하셨군요
이해했습니다
이대로 진행하셔도 좋겠네요!

2024-09-08 14:30 UTC, JHZLO commented on src/main/java/racingcar/constant/ErrorMessage.java
> +    public static final String INVALID_CAR_NAME_MIN = "자동차 이름은 5자 이하만 가능합니다.";
확장성 측면에서도 좋은 것 같습니다 👍

2024-09-08 14:54 UTC, JHZLO commented on src/main/java/racingcar/domain/RandomNumberGenerator.java
> +}
> `domain`은 보통 애플리케이션의 핵심 비즈니스 로직과 관련된 클래스들이 위치한다.

> `Service`는 일반적으로 도메인 모델과는 별개로 비즈니스 로직을 조정하거나 도메인 모델을 호출하는 로직을 처리합니다.

`RandomNumberGenerator`는 도메인 모델 안에서 중요한 비즈니스 로직과 밀접합니다.
그러므로 `Service`보다는 `Domain`에 속하는 것이  더 좋다고 생각합니다.

---

> `Car` `Model`에 속하는 것?

저는 `RandomNumberGenerator`를 따로 객체로 생성하는 것이 다음과 같은 이유에서 이점이 있다고 생각합니다.
1. 단일 책임 원칙
`Car` 객체에서 난수 생성과 같은 부수적인 작업을 담당하는 것은 책임의 분산을 초래할 수 있습니다.
`RandomNumberGenerator`를 분리하면 난수 생성은 해당 객체의 책임으로 명확하게 구분되므로, 
유지보수성이 높아진다고 생각합니다.

2. 확장성
난수 생성 로직이 앞으로 확장이 될 가능성이 있다면 따로 분리하는 것이 좋다고 생각합니다.
또한 `유연성`의 측면에서도 [전략 패턴](https://victorydntmd.tistory.com/292)으로 확장시킬 수 있습니다.

이러한 이유로 `RandomNumberGenerator`를 domain에 포함시켰으며 따로 객체로 만들어 `Car`로 부터 분리시켰습니다.

@digitpic 님의 생각도 궁금합니다!

2024-09-08 14:54 UTC, JHZLO commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +    }
별다른 이유 없는 것 같습니다.
생략하도록 하겠습니다!

2024-09-08 15:04 UTC, JHZLO commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +}
> `DTO`는 주로 `Controller`와 `Service` 또는 `Domain` 계층 사이에서 데이터를 전달하는 역할을 합니다.

### 계층 간의 명확한 역할 분리

`CarsDTO`를 사용하면 `Controller`가 `Domain` 객체를 직접 다루지 않고, 데이터 전달 역할만을 수행할 수 있게 됩니다.

이로 인해 `계층 간 결합도`가 낮아지며,
`Controller`가 `Domain` 로직에 의존하지 않고 데이터 전달에만 집중할 수 있게 됩니다. 

이러한 중간 계층이 존재하지 않게 되면 데이터 변환 및 관리 측면에서 의존성이 심해진다고 생각합니다.

---

### 유지 보수성과 확장성

나중에 `Cars 리스트`를 받아오는 방식이 달라지거나, 
추가적인 데이터 처리 과정이 필요할 경우 `DTO 내부`에서 변환 로직을 변경하면 되므로 
`유연성`의 측면에서도 향상된다고 생각합니다.

---

### 데이터 보안 및 무결성 보장

`DTO`는 도메인 객체와는 별개의 객체로써, 
외부에서 데이터를 전달받거나 노출할 때 중요한 `Domain` 객체를 직접 노출하지 않고 안전하게 데이터를 전달할 수 있습니다.

2024-09-08 15:13 UTC, JHZLO commented on src/main/java/racingcar/domain/Movable.java
> +    }
다시 한번 생각해보게 되는 질문인 것 같습니다 👍 

다음과 같이 정리를 해보았는데,

| 특성             | 인스턴스 생성                            | 정적 메서드                                |
|------------------|------------------------------------------|--------------------------------------------|
| **상태 유지**    | 가능                                     | 불가능 (상태 없음)                         |
| **다형성**        | 가능 (다른 구현체 주입 가능)              | 불가능 (고정된 동작)                       |
| **의존성 주입**   | 가능                                     | 불가능                                    |
| **테스트**       | 모의 객체를 사용하여 테스트 가능           | 테스트 시 난수 생성 등 무작위성을 제어하기 어려움 |
| **유연성**       | 높음 (다양한 구현체로 교체 가능)          | 낮음 (고정된 동작)                         |
| **간편성**       | 상대적으로 복잡 (인스턴스 필요)            | 간편 (인스턴스 불필요)                     |

단순히 `가독성` 측면에서 바라보았을 때는 `static`을 활용하여 클래스 자체를 사용하는 경우가 좋을지언정,
`테스트`와 `유연성` 측면에서 바라보았을 때는 인스턴스를 생성하는 것이 더 좋다고 생각합니다.

하지만, `인스턴스`를 생성한다고 해도 그렇게 가독성이 저하되지 않으므로,
이점이 높은 `인스턴스 생성`이 적합하다고 생각합니다.

@digitpic 님은 어떻게 생각하시는지 궁금합니다!

2024-09-08 15:18 UTC, JHZLO commented on src/main/java/racingcar/domain/Movable.java
> +}
위에서 설명드린 `RandomNumberGenerator`를 따로 객체로 분리한 이유와 거의 동일합니다.

1. **단일 책임 원칙**
`전진 여부 판단`이라는 책임을 `Car`에서 분리함으로써 역할의 명확성을 부여하였습니다.

2. **재사용성 증가**

3. **유연한 변경 가능성**
사전에 언급드린 `전략 패턴`으로 진화가 가능하며, 
복잡한 전진 로직을 추가해야 한다면 `Movable` 클래스를 변경하는 것으로 충분하게 됩니다.

4. **유지보수성**

이러한 이유 때문에 따로 `Movable` 객체를 생성하였습니다.

2024-09-08 15:19 UTC, JHZLO commented on src/main/java/racingcar/domain/model/Cars.java
> +    private final List<Car> carList;
좋은 지적 감사합니다!

반영하도록 하겠습니다 👍

2024-09-08 23:44 UTC, digitpic commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
클래스를 직접 사용하냐, 인스턴스를 생성해 사용하냐에 따른 특성을 알지 못했는데 덕분에 알게 되었습니다 감사합니다
인스턴스를 생성하는 게 객체지향적이기에 더 적합하다는 생각이 들었습니다

UI를 담당하는 부분은 테스트를 진행하지 않기에
`View` 에 있어서는 클래스를 직접 사용하는 게 좋겠다고 생각했습니다

그리고 단위 테스트를 진행해야 하는 `Controller`, `Service`, `Model` 은 인스턴스를 생성하는 게 좋겠다고 생각합니다

2024-09-08 23:46 UTC, digitpic commented on src/main/java/racingcar/view/InputView.java
> +    }
이번 주차부터는 `view` 에는 로직을 담지 않아보는 건 어떨까요?

권장되지 않을 뿐더러 테스트를 위한 메서드를 생성해야 한다는 단점이 있다고 보입니다

현재 구성대로라면 테스트를 위한 메서드가 필수적이긴 하겠네요

2024-09-08 23:52 UTC, digitpic commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +}
`controller` 는 `model` 에 의존해야 한다고 알고 있는데 제가 혹시 잘못 알고 있는 걸까요?
그렇기에 저는 `controller` 에 `model` 을 직접 사용하게 했습니다

2024-09-08 23:53 UTC, digitpic commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
저 또한 한 라인에 `.` 이 여러 개가 포함되는 경우를 피하려고 합니다
동의합니다

2024-09-08 23:58 UTC, digitpic commented on src/main/java/racingcar/domain/model/Car.java
> +    private int distance = 0;
상수는 변하지 않는 수라는 점을 놓치고 있었네요
이 경우라면 리터럴을 사용해야 할 수 밖에 없겠다는 생각이 듭니다
찾아보고 다른 방법이 있다면 코멘트 추가로 남기겠습니다

2024-09-09 01:26 UTC, digitpic commented on src/main/java/racingcar/domain/Movable.java
> +    }
확실히 인스턴스를 생성해 처리하는 경우의 이점이 더 많네요!
잘 정리해주셔서 이해하기 쉬웠습니다

저는 이제부터 view는 클래스를 통해 사용하고자 하고
controller, service, model은 인스턴스 생성을 통해 사용하고자 합니다!

2024-09-09 01:58 UTC, JHZLO commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
좋은 접근이네요. 동의합니다.

2024-09-09 01:59 UTC, JHZLO commented on src/main/java/racingcar/view/InputView.java
> +    }
넵 이번 주차에는 `view`에 로직을 담지 않고 구성해보도록 하겠습니다!

좋은 지적 감사합니다.

2024-09-09 02:02 UTC, JHZLO commented on src/main/java/racingcar/view/InputView.java
> +    }
규원님 말을 들어보니 테스트를 위한 메서드 작성과
`View`에 로직이 담겨있으면 `복잡성`만 증가할 것 같네요.

이번 주차부터는 피드백 반영해서 진행해보도록 하겠습니다!

2024-09-09 02:32 UTC, JHZLO commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +}
음.. 의존하는 것은 맞지만 `한쪽만 의존하는 관계` 관점으로 접근해야할 것 같습니다.

규원님의 말처럼,
`Controller`는 `Model`을 조작하고 상호작용하기에 `Model`과의 의존성이 필연적입니다.
하지만, `Model` 그 자체가 `Controller`에 의존하는 구조는 아닙니다.
즉, `강한 결합`이 아니라, `느슨한 결합`이므로  `DTO`를 삽입해도 괜찮다고 생각합니다.

만약 `강한 결합`의 디자인 패턴이라면, 
`DTO` 삽입 시에 결합도가 증가하고 `순환 의존성`문제가 발생하여 오히려 복잡도가 증가할 수 있습니다.

---

하지만 위와 같은 경우는 `느슨한 결합`이기에 오히려 `DTO`라는 중간계층을 삽입함으로써

`View` -> `Controller` -> `DTO` -> `Model` 로 데이터 접근이 가능해집니다.

이렇게 되었을 때,

- 계층 간 의존성 감소
-  유지보수성과 확장성
-  Model의 내부 구조를 감춤

의 설계상 이점을 챙길 수 있게 됩니다.

정리하자면 `DTO`가 삽입 되면 데이터 교환 방식에서의 의존성 감소가 되어 유연해집니다.
그렇다고 `Controller`가 `Model`의 의존 관계가 없어지는 것이 아닌, 비즈니스 로직을 호출하고 처리하는 `기능적 의존성`은 그대로 유지됩니다.

2024-09-09 02:54 UTC, JHZLO commented on src/main/java/racingcar/view/OutputView.java
> +        System.out.println();  // 라운드마다 결과 구분을 위한 빈 줄 출력
빈 줄 출력도 엄연한 "출력"의 역할을 담당하므로
저는 당연히 OutputView에서 구현해야 한다고 생각했습니다!

2024-09-09 02:56 UTC, JHZLO commented on src/main/java/racingcar/controller/RacingCarController.java
> +    }
오 좋은 접근인 것 같습니다!

그렇게 되면 어떠한 관점으로 봐도
`하나의 메서드가 하나의 일을 한다`라는 법칙에서 벗어나지 않고
제가 원하는 흐름대로 `Controller` 구현도 가능해질 것 같습니다.

좋은 피드백 감사합니다.

2024-09-09 03:00 UTC, digitpic commented on src/main/java/racingcar/domain/RandomNumberGenerator.java
> +}
`model`과 `domain`의 차이를 알고 나니
말씀해주신대로 현재 상태 유지하는 게 좋아보이네요

2024-09-09 03:03 UTC, JHZLO commented on src/main/java/racingcar/domain/Movable.java
> +    }
규원님의 의견에 동의합니다. 

`View`와 같이 state를 가지지 않는 객체는 클래스를 통해 사용하고
state를 가지는 객체인 `service`와 `model`은 인스턴스 생성을 통해서 유연성을 높이고자 할 계획입니다!

2024-09-09 03:09 UTC, digitpic commented on src/main/java/racingcar/domain/dto/CarsDTO.java
> +}
DTO의 활용성에 대해 잘 알지 못했는데 덕분에 알게 되었습니다
감사합니다

2024-09-09 03:24 UTC, digitpic commented on src/main/java/racingcar/exception/InputCarNamesValidator.java
> +    }
예외 케이스에 대해서도 더 깊게 생각해보는 시간을 가진다면 더 좋아질 수 있을 것 같아요

2024-09-09 03:24 UTC, digitpic commented on src/main/java/racingcar/exception/InputCarNamesValidator.java
validator를 exception에 둔 이유를 알고 싶습니다
저는 service에 가깝다고 생각하기 때문입니다

2024-09-09 03:24 UTC, digitpic commented on src/main/java/racingcar/exception/InputRoundValidator.java
> +        }
[isEmpty, isBlank 차이](https://hianna.tistory.com/531)에 대해서도 알아보시길 추천드립니다

2024-09-09 03:24 UTC, digitpic commented on src/main/java/racingcar/exception/InputRoundValidator.java
> +        }
아래 두 가지 방법도 고려해보면 좋을 거 같습니다

1. 정수로 변환 과정 중 예외 발생 시 예외 던지기
```suggestion
try {
    Integer.parseInt(input);
} catch (NumberFormatException e) {
    throw new IllegalArgumentException(INPUT_NOT_INTEGER);
}
```

2. 정규표현식 사용
- 이 부분은 저도 아직 미숙하지만 간결하며 강력하기에 익혀두시기를 추천드립니다
```suggestion
if (!input.matches("\\d+")) {
    throw new IllegalArgumentException(INPUT_NOT_INTEGER);
}
```

2024-09-09 03:24 UTC, digitpic commented on src/main/java/racingcar/service/GameService.java
> +    }
한 줄 안에서 처리하려고 하기보다 여러 줄로 나누어 처리하는 게 더 좋을 거 같습니다

2024-09-09 04:05 UTC, digitpic requested changes

2024-09-09 04:05 UTC, cueon commented on src/test/java/racingcar/view/InputCarsTest.java
가독성을 위해 assertJ 사용 추천드립니다

2024-09-09 04:05 UTC, cueon commented on src/test/java/racingcar/view/InputRoundTest.java
> +        Assertions.assertEquals(5, progressCount);
Assertions는 import 했기에 생략해도 좋아보입니다

2024-09-09 04:05 UTC, cueon commented on src/test/java/racingcar/view/InputRoundTest.java
`assertThat` , `assertThatThrownBy` 사용 추천드립니다

2024-09-09 04:05 UTC, cueon commented on src/test/java/racingcar/domain/MovableTest.java
랜덤에 대한 테스트를 위해 메서드 오버라이드도 좋지만
테스트 가능하도록 메서드를 구성하는 방법도 있습니다

[관련 정보](https://velog.io/@mohai2618/1.-Random%EA%B0%92)를 읽어보시면 도움이 될 거 같습니다

2024-09-09 04:05 UTC, cueon commented on src/test/java/racingcar/domain/CarTest.java
> +    }
given, when, then 단계를 적는 습관이 들면 더 좋을 거 같아요

2024-09-09 04:05 UTC, cueon commented on src/test/java/racingcar/domain/CarTest.java
> +    }
하나의 메서드에 테스트 두 개가 포함되었다고 생각하고
중복되는 코드도 많다고 생각합니다

2024-09-09 04:05 UTC, digitpic commented on src/test/java/racingcar/domain/CarsTest.java
> +        });
중복이 너무 많습니다
아래와 같은 방법은 어떨까요?

```suggestion
// given
Movable movable = new Movable() {
    @Override
    public boolean canMove() {
        return true;
    }
}

// when
pobi.moveForward(movable);
woni.moveForward(movable);
```

2024-09-09 04:05 UTC, digitpic commented on src/test/java/racingcar/domain/CarsTest.java
> +        assertEquals("pobi", winnerCars.get(0).getCarName());
given when then 에 대한 주석 적어주는 습관 좋은 거 같습니다

2024-09-09 09:03 UTC, digitpic commented
## 정리

### MVC
1. `View` 에 로직 담지 않기
2. `View` 는 인스턴스 생성 없이 클래스로 사용, `Controller`, `Service`, `Domain` 은 인스턴스 생성 해 사용하기

---
### 상수
1. 상수는 `Enum` + `toString()` 오버라이드해서 사용하기
2. 메시지 상수에 포함되는 숫자 또한 상수로 분리하기

---
### 테스트 코드
1. 테스트 코드 작성 시 given, when, then 단계에 맞춰 주석 처리하기
2. 테스트 코드 작성 시 가독성을 위해 `AssertJ` 문법 사용하기
3. 테스트를 위한 메서드를 만들지 말고, 테스트 하기 좋은 메서드를 생성하기
4. 하나의 테스트는 하나만 검증하기

---
### 구현 코드
1. 정수 검증 로직 개선하기
2. 너무 한 라인 안에 표현하지 않기
3. 별 다른 이유가 없다면 생략할 수 있는 내용 생략하기
4. `변수명` 에 자료구조 담지 않기
5. `String.trim()` 대신 `String.strip()` 사용하기
6. `String.isEmpty()` 와 `String.isBlank()` 차이 구분하기

2024-09-09 10:36 UTC, JHZLO commented on src/test/java/racingcar/domain/CarsTest.java
> +        });
훨씬 간결해지네요..

좋은 지적 감사합니다!

2024-09-09 10:37 UTC, JHZLO commented on src/test/java/racingcar/domain/CarTest.java
> +    }
좋은 지적 감사합니다.
수정하도록 하겠습니다.

2024-09-09 10:38 UTC, JHZLO commented on src/test/java/racingcar/domain/MovableTest.java
오 이런식으로도 접근이 가능하군요..!

좋은 정보 감사합니다.

2024-09-09 10:39 UTC, JHZLO commented on src/test/java/racingcar/view/InputRoundTest.java
> +        Assertions.assertEquals(5, progressCount);
꼼꼼한 리뷰 감사합니다!

2024-09-09 10:40 UTC, JHZLO commented on src/main/java/racingcar/service/GameService.java
> +    }
넵 반영하겠습니다.

2024-09-09 10:40 UTC, JHZLO commented on src/main/java/racingcar/exception/InputRoundValidator.java
> +        }
정규표현식.. 어렵지만 진짜 강력한 것 같습니다!

이번 주차때는 한 번 연습해봐야겠네요

꼼꼼한 리뷰 감사합니다.

2024-09-09 10:41 UTC, JHZLO commented on src/main/java/racingcar/exception/InputRoundValidator.java
> +        }
isBlank가 좀 더 상위의 개념이군요.

적극 사용해야겠네요 감사합니다!

2024-09-09 13:21 UTC, JHZLO commented on src/main/java/racingcar/exception/InputCarNamesValidator.java
`validator`라는 역할을 전달하고자 임의의 계층인 `exception`을 생성하였는데,

`service`에 가깝다는 것에 동의합니다!

`exception`을 만드는 게 오히려 계층의 흐름을 방해하는 것 같다는 느낌도 드네요
이번 주차에서는 그냥 `service`계층에서 구현해야겠습니다!

2024-09-10 07:07 UTC, JHZLO commented
1. View에 로직 담지 않기
2. enum 클래스를 사용해서 constant 구성하기 + Enum에 toString 메소드 활용해보기
3. 메시지 안에 있는 상수도 분리하기
4. 한 라인 안에 표현하지 않기
5. 변수명에 자료구조를 뜻하는 단어 포함하지 않기
6. String.strip() 사용하기
7. isBlank() 활용하기
8. Test 코드 작성시에 given, when, then 의 문법 구조에 맞게 작성하기
9. AssertJ를 활용하기
10. 테스트 하기 좋은 메서드를 작성하기

2024-09-10 07:07 UTC, closed without merging